# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kanna_02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kanna_02
  pod 'Kanna', '~>5.0.0'

end
